# autogenerated by txs
#include:color
#include:everypage
#include:graphicx
\SetWatermarkAngle{arg1}#S
\SetWatermarkColor#S
\SetWatermarkColor{arg1}#S
\SetWatermarkFontSize{arg1}#S
\SetWatermarkHorCenter{arg1}#S
\SetWatermarkLightness{arg1}#S
\SetWatermarkScale{arg1}#S
\SetWatermarkText{arg1}#S
\SetWatermarkVerCenter{arg1}#S
\sc#S
color.sty#S
everypage.sty#S
graphicx.sty#S
