# autogenerated by txs
\ExplFileDate#S
\ExplLoaderFileDate#S
\ProvidesExplClass#S
\ProvidesExplFile#S
\ProvidesExplPackage#S
\sys_if_output_dvi:F#S
\sys_if_output_dvi:T#S
\sys_if_output_dvi:TF#S
\sys_if_output_dvi_p:#S
\sys_if_output_pdf:F#S
\sys_if_output_pdf:T#S
\sys_if_output_pdf:TF#S
\sys_if_output_pdf_p:#S
l3backend-pdfmode.def#S
