# autogenerated by txs
#include:etoolbox
#include:ifluatex
#include:ifxetex
#include:keyval
#include:ltxcmds
\CurrentOption#S
\author#S
\csname#S
\ea#S
\expandafter#S
\maketitle#S
\noexpand#S
\thesis#S
\thesisload#S
\thesislong{arg1}{arg2}#S
\thesissetup{arg1}#S
\title{arg1}#S
