# autogenerated by txs
\Box#S
\Diamond#S
\Join#S
\leadsto#S
\mho#S
\sqsubset#S
\Box #S
\Diamond #S
\Join #S
\U/lasy/b/n#S
\U/lasy/m/n#S
\leadsto #S
\lhd #S
\lhd#S
\mho #S
\rhd #S
\rhd#S
\sqsubset #S
\sqsupset #S
\sqsupset#S
\symlasy#S
\unlhd #S
\unlhd#S
\unrhd #S
\unrhd#S
