# autogenerated by txs
#include:fontaxes
#include:fontspec
#include:ifluatex
#include:ifxetex
#include:xkeyval
\expandafter#S
\flafamily#S
\lato#S
\latofamily#S
fontaxes.sty#S
ifluatex.sty#S
ifxetex.sty#S
xkeyval.sty#S
